# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: 'lib/.*/patches/.*\.patch'
    -   id: end-of-file-fixer
        exclude: 'lib/.*/patches/.*\.patch'
    -   id: check-yaml
    -   id: check-json
        exclude: .vscode/ # vscode .json files have comments
    -   id: pretty-format-json
        files: CMakePresets.json
        args: ['--no-sort-keys', '--autofix']
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-case-conflict # in case somebody is using Windows
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.0
    hooks:
    -   id: clang-format
        types_or: [c++, c, cuda]
        # we want to keep the lib/ directory closer to the original source code
        exclude: ^lib/|tests/radius/eap_test_*
